Update gitmodules for the islet-assets repo split
islet-project/islet pull request #407
Opened 2024-12-10 13:20 UTC by Havner

I've created 4 repos for this:

3rd-android-kernel
3rd-gki-build
3rd-linux (for nw-linux and realm-linux)
3rd-kvmtool (for kvmtool and kvmtool-rim-measurer)

I didn't know the original repositories for the first two so they are just a copy&paste of the assets branch. More can be added in the future if required. For the latter two I've pushed some branches from the CCA upstream that we based our changes on.

The changed revision for kvmtool-rim-measurer is just a rebase to make the branches more consistent. It doesn't change any code.

2024-12-11 04:11 UTC, bitboom approved these changes

2024-12-11 04:52 UTC, nook1208 approved these changes

2024-12-12 09:43 UTC, p-sawicki2 requested changes
Shouldn't the changes in the .gitmodules be reflected also in the third-party folder?

2024-12-12 09:46 UTC, Havner commented
> Shouldn't the changes in the .gitmodules be reflected also in the third-party folder?

If the revision didn't change as it's the case here then no. I even commented on the one revision that did change.

2024-12-12 10:10 UTC, p-sawicki2 approved these changes

2024-12-12 11:00 UTC, merged